djangorestframework/runtests/urls.py
"""
Blank URLConf just to keep runtests.py happy.
"""
from django.conf.urls.defaults import *

urlpatterns = patterns('',
)

urls.py
from django.conf.urls.defaults import *
from loansProject.views import *
from loansProject.resources import *
from djangorestframework.views import *
from loansProject.apiviews import *

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs'
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    (r'^admin/', include(admin.site.urls)),

    # URL mappings for API calls
    (r'^api/activeLoanForCustomer/(?P<cust_id>\d+)/$', ActiveLoans.as_view()),

    (r'^api/paymentsBetween/(?P<cust_id>\d+)/$', PaymentsBetween.as_view()),
    (r'^api/paymentsBetween/(?P<cust_id>\d+)/s(?P<start>\d{8})/$', PaymentsBetween.as_view()),
    (r'^api/paymentsBetween/(?P<cust_id>\d+)/e(?P<end>\d{8})/$', PaymentsBetween.as_view()),
    (r'^api/paymentsBetween/(?P<cust_id>\d+)/s(?P<start>\d{8})/e(?P<end>\d{8})/$', PaymentsBetween.as_view()),

    (r'^api/loansTakenBetween/(?P<cust_id>\d+)/$', LoansTakenBetween.as_view()),
    (r'^api/loansTakenBetween/(?P<cust_id>\d+)/s(?P<start>\d{8})/$', LoansTakenBetween.as_view()),
    (r'^api/loansTakenBetween/(?P<cust_id>\d+)/e(?P<end>\d{8})/$', LoansTakenBetween.as_view()),
    (r'^api/loansTakenBetween/(?P<cust_id>\d+)/s(?P<start>\d{8})/e(?P<end>\d{8})/$', LoansTakenBetween.as_view()),

    (r'^api/loansWithOverdueInstallments/$', LoansWithOverdueInstallments.as_view()),
    (r'^api/loansWithOverdueInstallments/(?P<cust_id>\d+)/$', LoansWithOverdueInstallments.as_view()),

    (r'^api/loanHistory/(?P<cust_id>\d+)/$', LoanHistory.as_view()),

    (r'^api/paymentHistoryOfLoan/(?P<cust_id>\d+)/(?P<lname>[a-zA-Z0-9]+)/$', PaymentHistoryOfLoan.as_view()),

    (r'^api/defaulters/$', Defaulters.as_view()),

    (r'^api/paymentHistoryAllLoans/(?P<cust_id>\d+)/$', PaymentHistoryAllLoans.as_view()),

    (r'^api/monthlyInstallment/(?P<cust_id>\d+)/$', MonthlyInstallment.as_view()),

    (r'^api/loan/$', ListModelView.as_view(resource=LoanResource)),
    (r'^api/loan/(?P<pk>[^/]+)/$', InstanceReadOnlyModelView.as_view(resource=LoanResource)),

    (r'^api/customer/$', ListModelView.as_view(resource=CustomerResource)),
    (r'^api/customer/(?P<pk>[^/]+)/$', InstanceReadOnlyModelView.as_view(resource=CustomerResource)),

    (r'^api/activeLoan/$', ListModelView.as_view(resource=ActiveLoanResource)),
    (r'^api/activeLoan/(?P<pk>[^/]+)/$', InstanceReadOnlyModelView.as_view(resource=ActiveLoanResource)),

    (r'^api/completedLoan/$', ListModelView.as_view(resource=CompletedLoanResource)),
    (r'^api/completedLoan/(?P<pk>[^/]+)/$', InstanceReadOnlyModelView.as_view(resource=CompletedLoanResource)),

    (r'^api/payment/$', ListModelView.as_view(resource=PaymentResource)),
    (r'^api/payment/(?P<pk>[^/]+)/$', InstanceReadOnlyModelView.as_view(resource=PaymentResource)),

    (r'^api/overdueInstallment/$', ListModelView.as_view(resource=OverdueInstallmentResource)),
    (r'^api/overdueInstallment/(?P<pk>[^/]+)/$', InstanceReadOnlyModelView.as_view(resource=OverdueInstallmentResource)),

    (r'^api/application/$', ListModelView.as_view(resource=ApplicationResource)),
    (r'^api/application/(?P<pk>[^/]+)/$', InstanceReadOnlyModelView.as_view(resource=ApplicationResource)),

    (r'^api/supportTicket/$', ListModelView.as_view(resource=SupportTicketResource)),
    (r'^api/supportTicket/(?P<pk>[^/]+)/$', InstanceReadOnlyModelView.as_view(resource=SupportTicketResource)),

    # URL mappings for page views
    (r'^home/$',dueInstallments),
    (r'^dueInstallments/$', dueInstallments),
    (r'^allApplications/$', allApplications),
    (r'^allPayments/$', allPayments),
    (r'^cancelOrArchive/(archive)/(\d+)/$', cancelOrArchive),
    (r'^cancelOrArchive/(cancel)/(\d+)/$', cancelOrArchive),
    (r'^allLoans/$',allLoans),
    (r'^loanDetails/(\d+)/$',loanDetails),
    (r'^payInstallment/(\d+)/$', payInstallment),
    (r'^payInstallmentThanks/$', payInstallmentThanks),
    (r'^payPrepayment/(\d+)/$', payPrepayment),
    (r'^payPrepaymentThanks/$', payPrepaymentThanks),
    (r'^newApplication/$', newApplication),
    (r'^newApplicationThanks/$', newApplicationThanks),
    (r'^support/$', support),
    (r'^supportThanks/$', supportThanks),
)

urlpatterns += patterns('django.views.static',
                        (r'^home/(?P<path>.*)$','serve', {'document_root': 'staticMedia',}),
                        (r'^allApplications/(?P<path>.*)$','serve', {'document_root': 'staticMedia',}),
                        (r'^allLoans/(?P<path>.*)$','serve', {'document_root': 'staticMedia',}),
                        (r'^loanDetails/(\d+)/(?P<path>.*)$','serve', {'document_root': 'staticMedia',}),
                        (r'^dueInstallments/(?P<path>.*)$','serve', {'document_root': 'staticMedia',}),
                        (r'^allPayments/(?P<path>.*)$', 'serve', {'document_root': 'staticMedia',}),
                        (r'^base/(?P<path>.*)$', 'serve', {'document_root': 'staticMedia',}),
                        (r'^payInstallment/(\d+)/(?P<path>.*)$', 'serve', {'document_root': 'staticMedia',}),
                        (r'^payInstallmentThanks/(?P<path>.*)$', 'serve', {'document_root': 'staticMedia',}),
                        (r'^payPrepayment/(\d+)/(?P<path>.*)$', 'serve', {'document_root': 'staticMedia',}),
                        (r'^payPrepaymentThanks/(?P<path>.*)$', 'serve', {'document_root': 'staticMedia',}),
                        (r'^newApplication/(?P<path>.*)$', 'serve', {'document_root': 'staticMedia',}),
                        (r'^newApplicationThanks/(?P<path>.*)$', 'serve', {'document_root': 'staticMedia',}),
                        (r'^support/(?P<path>.*)$', 'serve', {'document_root': 'staticMedia',}),
                        (r'^supportThanks/(?P<path>.*)$', 'serve', {'document_root': 'staticMedia',}),
                        )

forms.py
from django import forms
from loans.models import *

class SupportForm(forms.Form):
  """ 
  Form Class for the support form.
  """
  complaintType = forms.ChoiceField(choices=COMPLAINT_TYPES)
  message = forms.CharField(widget=forms.Textarea)

  def __init__(self, customerId, data = None, initial = None):
    self.customerId = customerId
    super(SupportForm, self).__init__(data = data, initial = initial)
    self.fields['loan'] = forms.ModelChoiceField(queryset=Loan.objects.filter(customer__id=customerId), required=False)

  def clean_loan(self):
    """
    Validates whether the loan belongs to the customer.
    """
    loan = self.cleaned_data["loan"]
    if loan:
      if loan not in Loan.objects.filter(customer__id=self.customerId):
        raise forms.ValidationError('The loan provided is not valid.')
    else:
      return loan


class ApplicationForm(forms.Form):
  """
  Form Class for the new application form.
  """
  loanName = forms.CharField()
  loanAmount = forms.DecimalField(min_value=10000, decimal_places=2)
  loanCategory = forms.ChoiceField(choices=LOAN_TYPES)
  security = forms.ChoiceField(choices=SECURITY_TYPES)
  acceptedTerms = forms.BooleanField()


class PrepaymentForm(forms.Form):
  """
  Form Class for the pay prepayment form.
  """
  prepaymentAmount = forms.DecimalField()

  def __init__(self, loanId, data = None, initial = None):
    self.loanId = loanId
    super(PrepaymentForm, self).__init__(data = data, initial = initial)

  """
  Checks if the specified prepayment amount is less than the outstanding loan balance for a loan.
  """
  def clean_prepaymentAmount(self):
    formAmount = self.cleaned_data["prepaymentAmount"]
    maxAmount = Loan.objects.get(id=self.loanId).activeloan.outstandingLoanBalance
    if (formAmount > maxAmount):
      raise forms.ValidationError('Prepayment amount cannot be more than the outstanding amount for the loan.')
    else:
      return formAmount

templates/activeLoanDetails.html
{% extends 'base.html' %}
{% block title %}Active Loan Details{% endblock %}
<!--<link rel="stylesheet" type="text/css" href="style.css" />
</head>
<body>-->
{% block content %}
<h2>Loan Details</h2>
<h3 align="center">Your Loan is of Rs. {{details.principal}} at Rs. {{details.monthlyInstallment}} per months for next {{details.monthsLeft}} months</h3>
<table class="vertical" cellpadding="6.5px">
<tr class="out" onmouseover="this.className='over'" onmouseout="this.className='out'">
<td>Loan Name</td>
<td>{{details.name}}</td>
</tr>
<tr class="out" onmouseover="this.className='over'" onmouseout="this.className='out'">
<td>Loan Type</td>
<td>{{details.loanType}}</td>
</tr>
<tr class="out" onmouseover="this.className='over'" onmouseout="this.className='out'">
<td>Principal Amount (in Rs.)</td>
<td>{{details.principal}}</td>
</tr>
<tr class="out" onmouseover="this.className='over'" onmouseout="this.className='out'">
<td>Outstanding Amount (in Rs.)</td>
<td>{{details.outstandingAmount}}</td>
</tr>
<tr class="out" onmouseover="this.className='over'" onmouseout="this.className='out'">
<td>Monthly Installment (in Rs.)</td>
<td>{{details.monthlyInstallment}}</td>
</tr>
<tr class="out" onmouseover="this.className='over'" onmouseout="this.className='out'">
<td>Time Period (in months)</td>
<td>{{details.totalMonths}}</td>
</tr>
<tr class="out" onmouseover="this.className='over'" onmouseout="this.className='out'">
<td>Time Elapsed (in months)</td>
<td>{{details.monthsLeft}}</td>
</tr>
<tr class="out" onmouseover="this.className='over'" onmouseout="this.className='out'">
<td>Date Taken</td>
<td>{{details.dateTaken}}</td>
</tr>
<tr class="out" onmouseover="this.className='over'" onmouseout="this.className='out'">
<td>Expected Date of Termination</td>
<td>{{details.expTermination}}</td>
</tr>
<tr class="out" onmouseover="this.className='over'" onmouseout="this.className='out'">
<td>Next Installment due date</td>
<td>{{details.nextDueInstallment}}</td>
</tr>
<tr class="out" onmouseover="this.className='over'" onmouseout="this.className='out'">
<td>Interest Type</td>
<td>{{details.interestCategory}}</td>
</tr>
<tr class="out" onmouseover="this.className='over'" onmouseout="this.className='out'">
<td>Interest Rate</td>
<td>{{details.interestRate}}% p.a.</td>
</tr>
<tr class="out" onmouseover="this.className='over'" onmouseout="this.className='out'">
<td>Security</td>
<td>{{details.security}}</td>
</tr>
</table>

<br/>
<br/>
<h3>Payment History</h3>
{% if paymentDetails %}
<table class="long">
<tr class="top-row">
<th>Amount Paid (in Rs.)</th>
<th>Date of Payment</th>
<th>Payment Type</th>
<th>Merchant Used</th>
</tr>
{% for payment in paymentDetails %}
<tr class="out" onmouseover="this.className='over'" onmouseout="this.className='out'">
<td>{{payment.amount}}</td>
<td>{{payment.datePaid}}</td>
<td>{{payment.type}}</td>
<td>{{payment.merchant}}</td>
</tr>
{% endfor %}
</table>
{% else %}
<p>No payments made till now</p>
{% endif %}
{% endblock %}


templates/allPayments.html
{% extends 'base.html' %}
{% block title %}Payments{% endblock %}

{% block content %}
<h2>All Payments</h2>
{% if paymentsList %}
<table class="long">
<tr class="top-row">
<th>Loan Name</th>
<th>Amount Paid (in Rs.)</th>
<th>Payment Type</th>
<th>Payment Date</th>
</tr>
{% for payment in paymentsList %}
	<tr class="out" onmouseover="this.className='over'" onmouseout="this.className='out'"> 
	<td>{{payment.loan}}</td>
	<td>{{payment.amount}}</td>
	<td>{{payment.paymentType}}</td>
	<td>{{payment.datePaid}}</td>
	</tr>
{% endfor %}
</table>
{% else %}
<p>No payments till now</p>
{% endif %}
{% endblock %}

templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html>
	<head>
		<title>{% block title %}{% endblock %}</title>
		<link rel="stylesheet" type="text/css" href="Style.css" />
	</head>
	<body>
		
			<span id="apply_button" style="margin-top: 120px;" ><a href="/newApplication" id="top_button">Apply for<br>a new loan</a></span>
			<div id="topbar"><div id="banner">
                                <object width="728" height="90">
				<param name="movie" value="flashvortex.swf">
				<embed src="flashvortex.swf" width="728" height="90">
				</embed>
				</object>
			</div>
			</div>
		
		<div id="sidebar"  style="margin-top: 210px;">
			<div id="button1"><a href="/dueInstallments" id="side_button_1">Due Installments</a></div>
			<div id="button2"><a href="/allLoans" id="side_button_2">All Loans</a></div>
			<div id="button2"><a href="/allApplications" id="side_button_3">Active Applications</a></div>
			<div id="button2"><a href="/allPayments" id="side_button_4">Payment History</a></div>
			<div id="button2"><a href="/support" id="side_button_5">Support</a></div>
		</div>
		<div id="content">
		{% block content %}{% endblock %}
		</div>
	</body>
</html>

templates/completedLoanDetails.html
{% extends 'base.html' %}
{% block title %}Payments{% endblock %}

{% block content %}<h2>Completed Loan Details</h2>
<table class="vertical" cellpadding="6.5px">
<tr class="out" onmouseover="this.className='over'" onmouseout="this.className='out'">
<td>Loan Name</td>
<td>{{details.name}}</td>
</tr>
<tr class="out" onmouseover="this.className='over'" onmouseout="this.className='out'">
<td>Loan Type</td>
<td>{{details.loanType}}</td>
</tr>
<tr class="out" onmouseover="this.className='over'" onmouseout="this.className='out'">
<td>Principal Amount (in Rs.)</td>
<td>{{details.principal}}</td>
</tr>
<tr class="out" onmouseover="this.className='over'" onmouseout="this.className='out'">
<td>Time Period (in months)</td>
<td>{{details.totalMonths}}</td>
</tr>
<tr class="out" onmouseover="this.className='over'" onmouseout="this.className='out'">
<td>Date Taken</td>
<td>{{details.dateTaken}}</td>
</tr>
<tr class="out" onmouseover="this.className='over'" onmouseout="this.className='out'">
<td>Interest Type</td>
<td>{{details.interestCategory}}</td>
</tr>
<tr class="out" onmouseover="this.className='over'" onmouseout="this.className='out'">
<td>Interest Rate</td>
<td>{{details.interestRate}}% p.a.</td>
</tr>
<tr class="out" onmouseover="this.className='over'" onmouseout="this.className='out'">
<td>Security</td>
<td>{{details.security}}</td>
</tr>
</table>

<br/>
<br/>
<h3>Payment History</h3>
{% if paymentDetails %}
<table class="long">
<tr class="top-row">
<th>Amount Paid (in Rs.)</th>
<th>Date of Payment</th>
<th>Payment Type</th>
<th>Merchant Used</th>
</tr>
{% for payment in paymentDetails %}
<tr class="out" onmouseover="this.className='over'" onmouseout="this.className='out'">
<td>{{payment.amount}}</td>
<td>{{payment.datePaid}}</td>
<td>{{payment.type}}</td>
<td>{{payment.merchant}}</td>
</tr>
{% endfor %}
</table>
{% else %}
<p>No payments made till now.</p>
{% endif %}
{% endblock %}

templates/dueInstallments.html
{% extends 'base.html' %}
{% block title %}Due Installments{% endblock %}

{% block content %}
<h2>Due Installments</h2>
{% if overdueInstallments or dueInstallments %}
<table class="long" cellpadding="4px;">
{% if overdueInstallments %}
{% for inst in overdueInstallments %}
{% if forloop.first %}
<tr class="top-row">
<th>Loan Name</th>
<th>Due Installment Amount (in Rs.)</th>
<th>Due Date</th>
<th></th>
</tr>
{% endif %}
<tr class="overdue" onmouseover="this.className='overdue-over'" onmouseout="this.className='overdue'">
<td>{{inst.loan}}</td>
<td>{{inst.amount}}</td>
<td>{{inst.dueDate}}</td>
<td><a href="{{inst.payLink}}" id="button-link"><button>Pay Now</button></a></td>
</tr>
{% endfor %}
{% else %}
<tr class="top-row">
<th>Loan Name</th>
<th>Due Installment Amount (in Rs.)</th>
<th>Due Date</th>
<th></th>
</tr>
{% endif %}
{% if dueInstallments %}
{% for inst in dueInstallments %}
<tr class="out" onmouseover="this.className='over'" onmouseout="this.className='out'">
<td>{{inst.loan}}</td>
<td>{{inst.amount}}</td>
<td>{{inst.dueDate}}</td>
<td><a href="{{inst.payLink}}" id="button-link"><button>Pay Now</button></a></td>
</tr>
{% endfor %}
{% endif %}
</table>
{% else %}
<p>No due Installments</p>
{% endif %}
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block content %}
<p>Our bank offers various Loan services. Please sign in to avail them.</p>
{% endblock %}

templates/newApplication.html
{% extends 'base.html' %}
{% block title %}File a new loan application{% endblock %}
{% block content %}
<form submit="" method="post">
<table>
<tr>
  <th> <label for="id_loanName">Loan Name: </label>
  </th>
  <th> {{ form.loanName }}
  </th>
  <th> 
  {% if form.loanName.errors %}
      <ul>
      {% for error in form.loanName.errors %}
          <li><strong>{{ error|escape }}</strong></li>
      {% endfor %}
      </ul>
  {% endif %}
  </th>
</tr>
<tr>
  <th> <label for="id_loanAmount">Loan Amount: </label>
  </th>
  <th> {{ form.loanAmount }}
  </th>
  <th> 
  {% if form.loanAmount.errors %}
      <ul>
      {% for error in form.loanAmount.errors %}
          <li><strong>{{ error|escape }}</strong></li>
      {% endfor %}
      </ul>
  {% endif %}
  </th>
</tr>
<tr>
  <th> <label for="id_loanCategory">Loan Category: </label>
  </th>
  <th> {{ form.loanCategory }}
  </th>
  <th> 
  {% if form.loanCategory.errors %}
      <ul>
      {% for error in form.loanCategory.errors %}
          <li><strong>{{ error|escape }}</strong></li>
      {% endfor %}
      </ul>
  {% endif %}
  </th>
</tr>
<tr>
  <th><label for="id_security">Security:</label>
  </th>
  <th> {{ form.security }}
  </th>
  <th> 
  {% if form.security.errors %}
      <ul>
      {% for error in form.security.errors %}
          <li><strong>{{ error|escape }}</strong></li>
      {% endfor %}
      </ul>
  {% endif %}
  </th>
</tr>
<tr>
  <th><input type="checkbox" name="acceptedTerms" id="id_acceptedTerms" /> I accept the terms and conditions of the bank.
  </th>
  <th> 
  {% if form.acceptedTerms.errors %}
      <ul>
      {% for error in form.acceptedTerms.errors %}
          <li><strong>{{ error|escape }}</strong></li>
      {% endfor %}
      </ul>
  {% endif %}
  </th>
</tr>
<tr> <td align="center" colspan=2>
<input type="submit" value="Submit Application" />
</td> </tr>
</table>
</form>
{% endblock %} 

templates/newApplicationThanks.html
{% extends 'base.html' %}
{% block title %}Thank you!{% endblock %}

{% block content %}
<br/><br/><br/><br/><br/><br/>
<p align="center"> 
Your application has been filed.
</p>
{% endblock %}

templates/payInstallment.html
{% extends 'base.html' %}
{% block title %} Pay Installment{% endblock %}

{% block content %}
<form action="" method="post"> 
<h3>Loan Name:</h3> {{activeLoan.loan.name}} 
<h3>Installment due date:</h3> {{dueDate}} 
<h3>Current outstanding loan balance:</h3>Rs. {{outstandingLoanBalance}}
<h3>Installment Amount:</h3>Rs. {{installment}}
<p align="center">
<input type="submit" value="Proceed for payment" />
</p>
</form>
{% endblock %}

templates/payInstallmentThanks.html
{% extends 'base.html' %}
{% block title %}Thank you{% endblock %}

{% block content %}
<br/><br/><br/><br/><br/><br/>
<p align="center">
Thank you for paying the installment. Your payment has been registered and outstanding loan amount reduced accordingly.<br/>
Back to <a href="../dueInstallments">Home</a>
</p>
{% endblock %}

templates/payPrepayment.html
{% extends 'base.html' %}
{% block title %}Pay Prepayment for your loan{% endblock %}

{% block content %} 
<form action="" method="post">
<h3> Loan Name: </h3> {{ loanName }}
<h3> Amount to prepay:</h3>Rs. {{form.prepaymentAmount}}  
{% if form.prepaymentAmount.errors %}
    <ul>
    {% for error in form.prepaymentAmount.errors %}
        <li><strong>{{ error|escape }}</strong></li>
    {% endfor %}
    </ul>
{% endif %}
<p> *Note: Prepayment amount should be less than Rs. {{ outstandingAmount }}, the outstanding loan balance for your loan. </p>
<p align="center"><input type="submit" value="Proceed for Payment">  </p>
</form>
{% endblock %} 

templates/payPrepaymentThanks.html
{% extends 'base.html' %}
{% block title %} Thank you!{% endblock %}

{% block content %} 
<br/><br/><br/><br/><br/><br/>
<p align="center">
Your prepayment has been made for the loan.
</p>
{% endblock %} 

templates/support.html
{% extends 'base.html' %}
{% block title %} Happy to Help! {% endblock %}

{% block content %} 
<form submit="" method="post">
<table>
<tr>
  <th> Complaint Type:
  </th>
  <th> {{ form.complaintType }}
  </th>
  <th>
    {% if form.complaintType.errors %}
        <ul>
        {% for error in form.security.errors %}
            <li><strong>{{ error|escape }}</strong></li>
        {% endfor %}
        </ul>
    {% endif %}  
  </th>
</tr>
<tr>
  <th> Associated Loan:
  </th>
  <th> {{ form.loan }} 
  </th>
  <th>
    {% if form.loan.errors %}
        <ul>
        {% for error in form.loan.errors %}
            <li><strong>{{ error|escape }}</strong></li>
        {% endfor %}
        </ul>
    {% endif %}  
  </th>
</tr>
<tr>
  <th> Message:
  </th>
  <th> {{ form.message }}
  </th>
  <th>
    {% if form.message.errors %}
        <ul>
        {% for error in form.message.errors %}
            <li><strong>{{ error|escape }}</strong></li>
        {% endfor %}
        </ul>
    {% endif %}  
  </th>
</tr>
<tr> <td align="center" colspan=2;>
<input type="submit" value="Submit Application" />
</td> </tr>
</table>
</form>
{% endblock %} 

templates/supportThanks.html
{% extends 'base.html' %}
{% block title %}Thank you!{% endblock %}

{% block content %} 
<br/><br/><br/><br/><br/><br/>
<p align="center">
We have successfuly received your support request. Our customer care executive with get back to you soon.
</p>
{% endblock %} 